### ISSUE TITLE
Android 11 restriction

### ISSUE THREAD

**Issue by dashkevychdmytro** [perihanmirkelam/IPC-Examples#1]
Hi!
Start from Android 11 AIDL and Messenger examples doesn't work.

For fix this update Android Manifest needed.

For server side:
```
    <queries>
        <package android:name="com.pmirkelam.ipcclient" />
    </queries>
```

For client side:
```
    <queries>
        <package android:name="com.pmirkelam.ipcserver" />
    </queries>
```

**Comment by perihanmirkelam** [comment]
Issue was solved with merge pr https://github.com/perihanmirkelam/IPC-Examples/pull/2. Thanks for your contribution @dashkevichdmitry and @isakulaksiz
